<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="INHYIZLP12037" name="com.tng.ohrm.OhrmAddEmployee_Report" tests="3" failures="1" timestamp="28 Apr 2018 04:40:58 GMT" time="8.034" errors="0">
  <testcase name="openApplication" time="8.034" classname="com.tng.ohrm.OhrmAddEmployee_Report">
    <failure type="java.lang.AssertionError" message="Failing since correct page is notopened successfully">
      <![CDATA[java.lang.AssertionError: Failing since correct page is notopened successfully
at org.testng.Assert.fail(Assert.java:96)
at com.tng.ohrm.OhrmAddEmployee_Report.openApplication(OhrmAddEmployee_Report.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- openApplication -->
  <testcase name="Login" time="0.000" classname="com.tng.ohrm.OhrmAddEmployee_Report">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase name="AddEmployee" time="0.000" classname="com.tng.ohrm.OhrmAddEmployee_Report">
    <skipped/>
  </testcase> <!-- AddEmployee -->
</testsuite> <!-- com.tng.ohrm.OhrmAddEmployee_Report -->
